export const rotaDialogue = {
  home: [
    "Bir bölüm daha?",
    "Bugün hangi dünyaya kaçıyoruz?",
    "Yeni bir favori hissediyorum.",
    "Rafında biraz yıldız tozu var.",
    "Açılışı atlamıyoruz, değil mi?",
    "Ben rotayı çizdim. Sen seç.",
    "Bir sezon daha sığdırabiliriz.",
    "Kalbin hangi türe kayıyor?",
    "Battaniye hazırsa başlayalım.",
    "Tesadüfen iyi anime bulunmaz. Ben bulurum.",
  ],
  catalogue: [
    "Ne arıyoruz?",
    "İpucu ver, rafı ben bulayım.",
    "Tür mü, stüdyo mu, his mi?",
    "Dokuz yüz dünya. Sakin ol.",
    "Arama büyüsü hazır!",
    "Adını unuttuysan birlikte buluruz.",
    "Bir kelime söyle, izini süreyim.",
    "Bugün radarımız açık.",
    "Kötü seçimleri sessizce eliyorum.",
    "Filtreler bende, merak sende.",
  ],
  list: [
    "Rafına göz kulak oluyorum!",
    "Kaldığın bölümü ben unutmadım.",
    "Bu rafın lore'u epey derin.",
    "Planlananlar bana bakıp duruyor.",
    "Yarım kalan macera var mı?",
    "Puanlarını yargılamıyorum. Pek.",
    "Düzenli raf, huzurlu zihin.",
    "Bir final daha işaretleyelim mi?",
    "Burada her anime yerini biliyor.",
    "Raf nöbeti bende.",
  ],
  detail: [
    "İyi seçim!",
    "Buna bir şans ver derim.",
    "Spoiler yok. Söz.",
    "Künye önümde, karar senin.",
    "Bu dünyanın kapısı burada.",
    "Bölüm sayısını görünce korkma.",
    "Önce bir bölüm. Sonrasını biliyoruz.",
    "Rafa eklemek için göz kırpıyor.",
    "Ben olsam açılışı da dinlerdim.",
    "Not defterimi açtım.",
  ],
  accountReady: [
    "Rafın hazır!",
    "Her şey yerli yerinde.",
    "Bulut sakin, raf güvende.",
    "Hesap merkezi ışıl ışıl.",
    "Rotan sana bağlı.",
    "Kayıtların nöbetimde.",
  ],
  accountSyncing: [
    "Rafları buluşturuyorum…",
    "İki cihaz, tek rota…",
    "Yıldızları hizalıyorum…",
    "Kayıtlar yola çıktı…",
    "Bulutla kısa bir konuşmam var…",
    "Tombstone'ları da sayıyorum…",
  ],
  accountSuccess: [
    "Rafların buluştu!",
    "Eşitleme pürüzsüz geçti!",
    "İki taraf da aynı fikirde!",
    "Bulut görevini yaptı!",
    "Kayıtlar evine ulaştı!",
    "Rota yeniden tek parça!",
  ],
  accountError: [
    "Bağlantı biraz huysuz.",
    "Bir düğüm var, çözeriz.",
    "Bulut bugün tersinden kalkmış.",
    "Raf güvende; yalnız yol kapalı.",
    "Panik yok, yerel kayıt burada.",
    "Bir kayda yakından bakmalıyız.",
  ],
  listLoading: [
    "Rafları sayıyorum…",
    "Kitaplık açılıyor…",
    "Kayıtları sıraya diziyorum…",
    "Bir saniye, son raf kaldı…",
    "Tozları alıp geliyorum…",
    "Anime köşen hazırlanıyor…",
  ],
  listError: [
    "Bir şey ters gitti…",
    "Rafın anahtarı takıldı.",
    "Bu sayfa biraz nazlandı.",
    "Katalogla aramızda parazit var.",
    "Rotayı yeniden hesaplıyorum.",
    "Kayıtlar güvende; kapı açılmadı.",
  ],
  listEmpty: [
    "İlk favorin kim?",
    "Bu raf yeni bir hikâye istiyor.",
    "Boş raf, sınırsız ihtimal.",
    "İlk animeyi birlikte seçelim.",
    "Buraya güzel bir başlangıç yakışır.",
    "Bir keşif turuna ne dersin?",
  ],
  listCelebration: [
    "Son bölüm de tamam!",
    "Final gördük!",
    "Bir macera daha arşivde!",
    "Kapanış şarkısı bizden!",
    "Rafa bir yıldız daha!",
    "Bölüm sayacı zafer ilan etti!",
  ],
  listFilterEmpty: [
    "Bu raf bomboş!",
    "Burada henüz ayak izi yok.",
    "Yan rafta bir şeyler olabilir.",
    "Bu köşe şimdilik sessiz.",
    "Filtre biraz fazla seçici oldu.",
    "Başka bir raf deneyelim.",
  ],
  sharedLoading: [
    "Paylaşılan rafı arıyorum…",
    "Bağlantının izini sürüyorum…",
    "Misafir kapısı açılıyor…",
    "Rotayı yıldızlardan okuyorum…",
    "Raf birazdan görünecek…",
    "Paylaşım kodunu çözüyorum…",
  ],
  sharedClosed: [
    "Bu rota iz bırakmamış.",
    "Kapı şu an kapalı.",
    "Bu yıldız haritası eskimiş.",
    "Bağlantı başka bir yola sapmış.",
    "Raf sahibi perdeyi çekmiş.",
    "Güncel bir rota istemeliyiz.",
  ],
  sharedError: [
    "Bağlantı biraz huysuz.",
    "Misafir kapısı sıkıştı.",
    "Rota sinyali çok zayıf.",
    "Bu raf şimdilik uzakta.",
    "Bağlantıyı yeniden dinliyorum.",
    "Yol var, ama sis de var.",
  ],
  sharedWelcome: [
    "Misafirimiz var!",
    "Başkasının rafına hoş geldin.",
    "Sessizce göz atıyoruz, tamam mı?",
    "Yeni bir anime yolcusu!",
    "Bu rotanın konuğuyuz.",
    "Raf turu başlasın!",
  ],
} as const;

export type RotaDialogueScene = keyof typeof rotaDialogue;

